on:
 push:  
  branches:
   - master
name: Build and deploy Python app
jobs:
 build-and-deploy:
  runs-on: ubuntu-latest
  steps:
  # checkout the repo
  - uses: actions/checkout@master 
  # setup python
  - name: Setup Python
    uses: actions/setup-python@v1
    with:
     python-version: 3.8
  # install dependencies
  - name: python install
    working-directory: Application
    run: |
     sudo apt install python3.8-venv
     python -m venv --copies antenv
     source antenv/bin/activate
     pip install setuptools
     pip install -r requirements.txt 
  # Azure login
  - uses: azure/login@v1
    with:
     creds: ${{ secrets.AZURE_CREDENTIALS }}
  - uses: azure/appservice-settings@v1
    with:
     app-name: testappviv
     general-settings-json: '{"linuxFxVersion": "PYTHON|3.8"}' #'General configuration settings as Key Value pairs'
  # deploy web app 
  - uses: azure/webapps-deploy@v2
    with:
     app-name: testappviv
     package: Application
     startup-command: gunicorn --bind=0.0.0.0 --timeout 600 app:app

  # Azure logout
  - name: logout
    run: |
     az logout
