# Python on Linux Web App
# Build a Python project (using Django/Flask/Bottle frameworks) and deploy it to Azure as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:
on:
  push:
    branches:
      - master

name: Build and deploy Python app
jobs:
 build-and-deploy:
  runs-on: ubuntu-latest
  steps:
  # checkout the repo 
  - uses: actions/checkout@master
  # setup python
  - name: Setup Python
    uses: actions/setup-python@v1
    with:
     python-version: 3.8
  # install dependencies
  - name: python install
    working-directory: Application 
    run: |
     sudo apt install python3.8-venv
     python -m venv --copies antenv
     source antenv/bin/activate
     pip install setuptools
     pip install -r requirements.txt
  # Azure login
  - uses: azure/login@v1
    with:
     creds: ${{ secrets.AZURE_CREDENTIALS_GITHUB_SECRET_b073 }}
  - uses: azure/appservice-settings@v1
    with:
     app-name: pythobase1
     general-settings-json: '{"linuxFxVersion": "PYTHON|3.8"}' #'General configuration settings as Key Value pairs'
  # deploy web app
  - uses: azure/webapps-deploy@v2
    with:
     app-name: pythobase1
     package: Application
     startup-command: gunicorn --bind=0.0.0.0 --timeout 600 app:app
  # Azure logout
  - name: logout
    run: |
     az logout